const express = require("express");
const { Telegraf } = require("telegraf");
const { Pool } = require("pg");

const BOT_TOKEN = process.env.BOT_TOKEN;
const ADMIN_TELEGRAM_ID = process.env.ADMIN_TELEGRAM_ID || "";
const ADMIN_PANEL_PASSWORD = process.env.ADMIN_PANEL_PASSWORD || "";
const MEDIA = {
  welcome: process.env.MEDIA_WELCOME || "",
  profile: process.env.MEDIA_PROFILE || "",
  rental: process.env.MEDIA_RENTAL || "",
  terms: process.env.MEDIA_TERMS || "",
  complaint: process.env.MEDIA_COMPLAINT || "",
  admin: process.env.MEDIA_ADMIN || "",
  warning: process.env.MEDIA_WARNING || "",
  blocked: process.env.MEDIA_BLOCKED || "",
  stars: process.env.MEDIA_STARS || "",
  returnNft: process.env.MEDIA_RETURN_NFT || "",
  withdrawal: process.env.MEDIA_WITHDRAWAL || "",
  support: process.env.MEDIA_SUPPORT || ""
};

async function getMedia(key) {
  if (MEDIA[key]) return MEDIA[key];
  if (pool) {
    const r = await dbQuery("SELECT file_id FROM bot_media WHERE media_key=$1",[key]);
    return r.rows[0]?.file_id || "";
  }
  return "";
}

async function sendVisual(ctx, key, text, extra = {}) {
  const media = await getMedia(key);
  if (media) return ctx.replyWithPhoto(media, { caption: text, ...extra });
  return ctx.reply(text, extra);
}

async function saveMedia(key, fileId) {
  if (pool) {
    await dbQuery("INSERT INTO bot_media (media_key,file_id) VALUES ($1,$2) ON CONFLICT (media_key) DO UPDATE SET file_id=EXCLUDED.file_id",[key,fileId]);
    return;
  }
}

async function editVisual(ctx, key, text, extra = {}) {
  // Telegram cannot attach a new photo to an existing text message with editMessageText.
  // Send a new visual message and remove the old one when possible.
  try { await ctx.deleteMessage(); } catch (e) {}
  return sendVisual(ctx, key, text, extra);
}



if (!BOT_TOKEN) {
  console.error("BOT_TOKEN is not configured");
  process.exit(1);
}

const bot = new Telegraf(BOT_TOKEN);

bot.catch((err, ctx) => {
  console.error("Telegram bot error:", err);
  try {
    if (ctx && ctx.chat) {
      ctx.reply("⚠️ Произошла внутренняя ошибка бота. Попробуйте ещё раз.").catch(() => {});
    }
  } catch (e) {}
});

const app = express();
app.use(express.json());

const pool = process.env.DATABASE_URL
  ? new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_URL.includes("localhost")
        ? false
        : { rejectUnauthorized: false }
    })
  : null;

const memory = {
  users: new Map(),
  listings: new Map(),
  rentals: new Map(),
  withdrawals: new Map(),
  warnings: new Map(),
  complaints: new Map(),
  nextListingId: 1,
  nextRentalId: 1,
  nextWithdrawalId: 1,
  nextWarningId: 1,
  nextComplaintId: 1
};

const states = new Map();

async function dbQuery(text, params = []) {
  if (!pool) return null;
  return pool.query(text, params);
}

async function initDb() {
  if (!pool) return;

  await dbQuery(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      telegram_id BIGINT,
      username TEXT,
      balance NUMERIC(18,2) NOT NULL DEFAULT 0,
      stars_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
      warnings INTEGER NOT NULL DEFAULT 0,
      blocked BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS listings (
      id SERIAL PRIMARY KEY,
      seller_id BIGINT NOT NULL,
      title TEXT NOT NULL,
      price NUMERIC(18,2) NOT NULL,
      duration_days INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS rentals (
      id SERIAL PRIMARY KEY,
      listing_id INTEGER NOT NULL,
      renter_id BIGINT NOT NULL,
      seller_id BIGINT NOT NULL,
      amount NUMERIC(18,2) NOT NULL,
      status TEXT NOT NULL DEFAULT 'paid',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS bot_media (
      media_key TEXT PRIMARY KEY,
      file_id TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS warnings (
      id SERIAL PRIMARY KEY,
      telegram_id BIGINT NOT NULL,
      reason TEXT NOT NULL,
      admin_id BIGINT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS complaints (
      id SERIAL PRIMARY KEY,
      telegram_id BIGINT NOT NULL,
      text TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'open',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS admin_actions (
      id SERIAL PRIMARY KEY,
      telegram_id BIGINT NOT NULL,
      action TEXT NOT NULL,
      amount NUMERIC(18,2),
      details TEXT,
      admin_id BIGINT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS withdrawals (
      id SERIAL PRIMARY KEY,
      telegram_id BIGINT NOT NULL,
      amount NUMERIC(18,2) NOT NULL,
      method TEXT NOT NULL,
      details TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  const migrations = [
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS id BIGINT`,
    `CREATE SEQUENCE IF NOT EXISTS users_id_seq AS BIGINT`,
    `DO $m$ DECLARE id_type TEXT; BEGIN
       SELECT format_type(a.atttypid, a.atttypmod)
       INTO id_type
       FROM pg_attribute a
       WHERE a.attrelid = 'users'::regclass
         AND a.attname = 'id'
         AND NOT a.attisdropped;

       IF id_type IN ('integer','bigint') THEN
         EXECUTE 'UPDATE users SET id = nextval(''users_id_seq'')::' || id_type || ' WHERE id IS NULL';
         EXECUTE 'ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval(''users_id_seq'')::' || id_type;
       ELSIF id_type = 'text' THEN
         EXECUTE 'UPDATE users SET id = nextval(''users_id_seq'')::text WHERE id IS NULL';
         EXECUTE 'ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval(''users_id_seq'')::text';
       END IF;
    END $m$`,
    `DO $m$ DECLARE max_id BIGINT; BEGIN
       SELECT COALESCE(MAX(id), 0)::bigint INTO max_id FROM users;
       IF max_id < 1 THEN max_id := 1; END IF;
       PERFORM setval(''users_id_seq'', max_id, true);
    END $m$`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_id BIGINT`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS balance NUMERIC(18,2) NOT NULL DEFAULT 0`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS stars_balance NUMERIC(18,2) NOT NULL DEFAULT 0`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS warnings INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked BOOLEAN NOT NULL DEFAULT FALSE`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `CREATE UNIQUE INDEX IF NOT EXISTS users_telegram_id_uq ON users (telegram_id)`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS seller_id BIGINT`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS title TEXT`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS price NUMERIC(18,2) DEFAULT 0`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS duration_days INTEGER DEFAULT 1`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active'`,
    `ALTER TABLE listings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS listing_id INTEGER`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS renter_id BIGINT`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS seller_id BIGINT`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2) DEFAULT 0`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'paid'`,
    `ALTER TABLE rentals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `ALTER TABLE warnings ADD COLUMN IF NOT EXISTS telegram_id BIGINT`,
    `ALTER TABLE warnings ADD COLUMN IF NOT EXISTS reason TEXT`,
    `ALTER TABLE warnings ADD COLUMN IF NOT EXISTS admin_id BIGINT`,
    `ALTER TABLE warnings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `ALTER TABLE complaints ADD COLUMN IF NOT EXISTS telegram_id BIGINT`,
    `ALTER TABLE complaints ADD COLUMN IF NOT EXISTS text TEXT`,
    `ALTER TABLE complaints ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'open'`,
    `ALTER TABLE complaints ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS telegram_id BIGINT`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS action TEXT`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2)`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS details TEXT`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS admin_id BIGINT`,
    `ALTER TABLE admin_actions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS telegram_id BIGINT`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2)`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS method TEXT`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS details TEXT`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending'`,
    `ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`
  ];

  for (const sql of migrations) {
    try {
      await dbQuery(sql);
    } catch (err) {
      console.error("DB migration failed:", sql, err);
      throw err;
    }
  }
}

async function ensureUser(ctx) {
  const id = ctx.from.id;
  const username = ctx.from.username || "";

  if (pool) {
    await dbQuery(
      `INSERT INTO users (telegram_id, username)
       VALUES ($1, $2)
       ON CONFLICT (telegram_id)
       DO UPDATE SET username = EXCLUDED.username`,
      [id, username]
    );
    return;
  }

  if (!memory.users.has(id)) {
    memory.users.set(id, { telegram_id: id, username, balance: 0 });
  } else {
    memory.users.get(id).username = username;
  }
}

async function getBalance(id) {
  if (pool) {
    const r = await dbQuery("SELECT balance FROM users WHERE telegram_id = $1", [id]);
    return Number(r.rows[0]?.balance || 0);
  }
  return Number(memory.users.get(id)?.balance || 0);
}

async function addBalance(id, amount) {
  if (pool) {
    await dbQuery(
      "INSERT INTO users (telegram_id, balance) VALUES ($1, $2) ON CONFLICT (telegram_id) DO UPDATE SET balance = users.balance + $2",
      [id, amount]
    );
    return;
  }
  if (!memory.users.has(id)) memory.users.set(id, { telegram_id: id, username: "", balance: 0 });
  memory.users.get(id).balance += Number(amount);
}

async function addStars(id, amount) {
  if (pool) {
    await dbQuery(
      "INSERT INTO users (telegram_id, stars_balance) VALUES ($1,$2) ON CONFLICT (telegram_id) DO UPDATE SET stars_balance = users.stars_balance + $2",
      [id, amount]
    );
    return;
  }
  if (!memory.users.has(id)) memory.users.set(id, { telegram_id:id, username:"", balance:0, stars_balance:0, warnings:0, blocked:false });
  const u=memory.users.get(id); u.stars_balance=(u.stars_balance||0)+Number(amount);
}

async function getProfile(id) {
  if (pool) {
    const u=(await dbQuery("SELECT telegram_id,username,balance,stars_balance,warnings,blocked FROM users WHERE telegram_id=$1",[id])).rows[0];
    const ws=(await dbQuery("SELECT id,reason,created_at FROM warnings WHERE telegram_id=$1 ORDER BY id DESC LIMIT 20",[id])).rows;
    return {user:u,warnings:ws};
  }
  const u=memory.users.get(id)||{telegram_id:id,username:"",balance:0,stars_balance:0,warnings:0,blocked:false};
  return {user:u,warnings:[...memory.warnings.values()].filter(x=>x.telegram_id===id).slice(-20).reverse()};
}

async function setBlocked(id, blocked) {
  if (pool) { await dbQuery("INSERT INTO users (telegram_id,blocked) VALUES ($1,$2) ON CONFLICT (telegram_id) DO UPDATE SET blocked=$2",[id,blocked]); return; }
  if (!memory.users.has(id)) memory.users.set(id,{telegram_id:id,username:"",balance:0,stars_balance:0,warnings:0,blocked:false});
  memory.users.get(id).blocked=blocked;
}

async function addWarning(id, reason, adminId) {
  if (pool) {
    await dbQuery("INSERT INTO warnings (telegram_id,reason,admin_id) VALUES ($1,$2,$3)",[id,reason,adminId]);
    await dbQuery("INSERT INTO users (telegram_id,warnings) VALUES ($1,1) ON CONFLICT (telegram_id) DO UPDATE SET warnings=users.warnings+1",[id]);
    return;
  }
  if (!memory.users.has(id)) memory.users.set(id,{telegram_id:id,username:"",balance:0,stars_balance:0,warnings:0,blocked:false});
  const u=memory.users.get(id); u.warnings=(u.warnings||0)+1;
  const wid=memory.nextWarningId++; memory.warnings.set(wid,{id:wid,telegram_id:id,reason,admin_id:adminId});
}

async function createComplaint(id, complaint) {
  if (pool) { const r=await dbQuery("INSERT INTO complaints (telegram_id,text) VALUES ($1,$2) RETURNING id",[id,complaint]); return r.rows[0].id; }
  const idn=memory.nextComplaintId++; memory.complaints.set(idn,{id:idn,telegram_id:id,text:complaint,status:"open"}); return idn;
}

async function getOpenComplaints() {
  if (pool) return (await dbQuery("SELECT * FROM complaints WHERE status='open' ORDER BY id ASC LIMIT 50")).rows;
  return [...memory.complaints.values()].filter(x=>x.status==="open").slice(0,50);
}

async function closeComplaint(id) {
  if (pool) { await dbQuery("UPDATE complaints SET status='closed' WHERE id=$1",[id]); return; }
  const x=memory.complaints.get(id); if(x) x.status="closed";
}

async function subtractBalance(id, amount) {
  if (pool) {
    const r = await dbQuery(
      "UPDATE users SET balance = balance - $2 WHERE telegram_id = $1 AND balance >= $2 RETURNING balance",
      [id, amount]
    );
    return r.rowCount === 1;
  }
  const user = memory.users.get(id);
  if (!user || user.balance < amount) return false;
  user.balance -= Number(amount);
  return true;
}

async function createListing(sellerId, title, price, durationDays, status = "active") {
  if (pool) {
    const r = await dbQuery(
      "INSERT INTO listings (seller_id, title, price, duration_days, status) VALUES ($1,$2,$3,$4,$5) RETURNING id",
      [sellerId, title, price, durationDays, status]
    );
    return r.rows[0].id;
  }
  const id = memory.nextListingId++;
  memory.listings.set(id, { id, seller_id: sellerId, title, price, duration_days: durationDays, status });
  return id;
}

async function activateListing(id, price, durationDays) {
  if (pool) {
    const r = await dbQuery(
      "UPDATE listings SET price=$2, duration_days=$3, status='active' WHERE id=$1 AND status='pending' RETURNING id",
      [id, price, durationDays]
    );
    return r.rowCount === 1;
  }
  const item = memory.listings.get(id);
  if (!item || item.status !== "pending") return false;
  item.price = Number(price);
  item.duration_days = Number(durationDays);
  item.status = "active";
  return true;
}

async function getListings() {
  if (pool) {
    const r = await dbQuery(
      "SELECT id, seller_id, title, price, duration_days FROM listings WHERE status='active' ORDER BY id DESC LIMIT 20"
    );
    return r.rows;
  }
  return [...memory.listings.values()].filter(x => x.status === "active").slice(-20).reverse();
}

async function getListing(id) {
  if (pool) {
    const r = await dbQuery("SELECT * FROM listings WHERE id=$1 AND status='active'", [id]);
    return r.rows[0];
  }
  return memory.listings.get(id);
}

async function createRental(listing) {
  if (pool) {
    const r = await dbQuery(
      "INSERT INTO rentals (listing_id, renter_id, seller_id, amount) VALUES ($1,$2,$3,$4) RETURNING id",
      [listing.id, currentPayment.renterId, listing.seller_id, listing.price]
    );
    return r.rows[0].id;
  }
  const id = memory.nextRentalId++;
  memory.rentals.set(id, {
    id,
    listing_id: listing.id,
    renter_id: currentPayment.renterId,
    seller_id: listing.seller_id,
    amount: Number(listing.price),
    status: "paid"
  });
  return id;
}

let currentPayment = { renterId: 0 };

async function recordRentalAndCredit(listing, renterId) {
  currentPayment.renterId = renterId;
  const rentalId = await createRental(listing);
  await addBalance(listing.seller_id, Number(listing.price));
  return rentalId;
}

async function createWithdrawal(id, amount, method, details) {
  if (pool) {
    const r = await dbQuery(
      "INSERT INTO withdrawals (telegram_id, amount, method, details) VALUES ($1,$2,$3,$4) RETURNING id",
      [id, amount, method, details]
    );
    return r.rows[0].id;
  }
  const wid = memory.nextWithdrawalId++;
  memory.withdrawals.set(wid, { id: wid, telegram_id: id, amount, method, details, status: "pending" });
  return wid;
}

async function getPendingWithdrawals() {
  if (pool) {
    const r = await dbQuery(
      "SELECT id, telegram_id, amount, method, details, created_at FROM withdrawals WHERE status='pending' ORDER BY id ASC LIMIT 50"
    );
    return r.rows;
  }
  return [...memory.withdrawals.values()].filter(x => x.status === "pending").slice(0, 50);
}

async function getWithdrawal(id) {
  if (pool) {
    const r = await dbQuery("SELECT * FROM withdrawals WHERE id=$1", [id]);
    return r.rows[0];
  }
  return memory.withdrawals.get(id);
}

async function updateWithdrawalStatus(id, status) {
  if (pool) {
    const r = await dbQuery(
      "UPDATE withdrawals SET status=$2 WHERE id=$1 AND status='pending' RETURNING telegram_id, amount",
      [id, status]
    );
    return r.rows[0] || null;
  }
  const w = memory.withdrawals.get(id);
  if (!w || w.status !== "pending") return null;
  w.status = status;
  return w;
}

function termsKeyboard() {
  return {
    reply_markup: {
      inline_keyboard: [
        [{ text: "✅ Я ознакомился с условиями", callback_data: "accept_terms" }],
        [{ text: "◀️ Назад", callback_data: "home" }]
      ]
    }
  };
}

function termsText() {
  return `📜 Условия сдачи NFT / подарков

Перед размещением подарка в аренду обязательно ознакомьтесь с правилами.

1. 🎁 Подарок должен принадлежать вам. Запрещено размещать чужие подарки без разрешения владельца.

2. 💰 Указывайте реальную и понятную цену аренды и срок аренды.

3. 📅 После начала аренды нельзя самовольно отзывать или передавать подарок другому пользователю до окончания оплаченного срока.

4. 🤝 Запрещены обман, мошенничество, фиктивные объявления и попытки получить оплату без предоставления аренды.

5. 🚫 За нарушение правил объявление может быть удалено, а аккаунт — ограничен или заблокирован.

6. 🛡️ Спорные ситуации рассматриваются администрацией сервиса. Решение принимается по данным об оплате и аренде.

7. 💸 Выплата продавцу производится на внутренний баланс бота после успешной оплаты аренды.

8. 🧾 При выводе средств пользователь обязан указывать корректные реквизиты. Ответственность за ошибочные реквизиты несёт пользователь.

9. ⚠️ Администрация может запросить дополнительную проверку по спорной операции.

10. 🔐 Никому не передавайте пароль, коды входа, коды Telegram или другие секретные данные.

Нажимая «Я ознакомился с условиями», вы подтверждаете, что прочитали и принимаете эти правила.`;
}

function rentalInstructionText() {
  return `📦 Как сдать NFT / подарок в аренду

Перед созданием объявления сначала передайте подарок боту.

🎁 Как передать подарок:
1. Откройте свой Telegram-подарок в профиле.
2. Нажмите кнопку действий с подарком.
3. Выберите действие передачи/отправки подарка.
4. В качестве получателя выберите этого бота.
5. После передачи вернитесь сюда и нажмите «✅ Подарок передан боту».

⚠️ Важно:
• Передавайте только тот подарок, которым вы действительно владеете.
• Не отправляйте пароль, код входа, код подтверждения или другие секретные данные.
• Если Telegram не показывает возможность передать этот подарок боту, не пытайтесь обходить ограничения — обратитесь в поддержку.
• Не размещайте один и тот же подарок одновременно в другом месте.

После этого бот попросит название, цену и срок аренды.`;
}

function rentalInstructionKeyboard() {
  return {
    reply_markup: {
      inline_keyboard: [
        [{ text: "✅ Подарок передан боту", callback_data: "continue_rent" }],
        [{ text: "📜 Условия сдачи NFT", callback_data: "terms" }],
        [{ text: "◀️ Назад", callback_data: "home" }]
      ]
    }
  };
}

function mainKeyboard() {
  return {
    reply_markup: {
      inline_keyboard: [
        [{ text: "🎁 Арендовать подарок", callback_data: "catalog" }],
        [{ text: "🎁 Сдать в аренду", callback_data: "rent_out" }],
        [{ text: "📜 Условия сдачи NFT", callback_data: "terms" }],
        [{ text: "📦 Мои аренды", callback_data: "rentals" }],
        [{ text: "👤 Профиль", callback_data: "profile" }],
        [{ text: "💰 Мой баланс", callback_data: "balance" }],
        [{ text: "🚨 Подать жалобу", callback_data: "complaint" }],
        [{ text: "💸 Вывести средства", callback_data: "withdraw" }],
        [{ text: "⭐ Пополнить Stars", callback_data: "stars" }],
        [{ text: "💬 Поддержка", callback_data: "support" }]
      ]
    }
  };
}

bot.start(async (ctx) => {
  await ensureUser(ctx);
  await sendVisual(ctx, "welcome", "🎁 Добро пожаловать в аренду уникальных Telegram-подарков!\n\nВыберите действие:", mainKeyboard());
});

bot.action("terms", async (ctx) => {
  await ctx.answerCbQuery();
  await editVisual(ctx, "terms", termsText(), termsKeyboard());
});

bot.action("accept_terms", async (ctx) => {
  await ctx.answerCbQuery("Условия приняты");
  await ensureUser(ctx);
  states.set(ctx.from.id, { step: "awaiting_gift", termsAccepted: true });
  await ctx.editMessageText(
    "✅ Условия приняты.\n\n" + rentalInstructionText(),
    rentalInstructionKeyboard()
  );
});

bot.action("continue_rent", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  states.set(ctx.from.id, { step: "title", termsAccepted: true });
  await ctx.editMessageText(
    "🎁 Отлично! Теперь напишите название подарка, который хотите сдать в аренду.\n\nНапример: «Весенний мишка» или название вашего NFT."
  );
});

bot.action("profile", async (ctx) => {
  await ctx.answerCbQuery(); await ensureUser(ctx);
  const p=await getProfile(ctx.from.id); const u=p.user;
  const warnings=p.warnings.length ? p.warnings.map((w,i)=>`\\n${i+1}. ${w.reason}`).join("") : "\\nНет предупреждений.";
  await ctx.editMessageText(`👤 Профиль\\n\\n🆔 ID: ${u.telegram_id}\\n👤 Username: ${u.username ? "@"+u.username : "не указан"}\\n💰 Баланс: ${Number(u.balance||0).toFixed(2)} ₽\\n⭐ Stars: ${Number(u.stars_balance||0).toFixed(0)}\\n⚠️ Предупреждений: ${Number(u.warnings||0)}\\n🔒 Статус: ${u.blocked ? "заблокирован" : "активен"}\\n\\n📋 Собранные предупреждения:${warnings}`,{reply_markup:{inline_keyboard:[[{text:"◀️ Назад",callback_data:"home"}]]}});
});

bot.action("complaint", async (ctx) => {
  await ctx.answerCbQuery(); await ensureUser(ctx); states.set(ctx.from.id,{step:"complaint"});
  await editVisual(ctx, "complaint", "🚨 Напишите текст жалобы. Укажите, на кого или на какую аренду она относится:");
});

bot.action("balance", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  const balance = await getBalance(ctx.from.id);
  await ctx.editMessageText(
    `💰 Ваш баланс\n\nДоступно: ${balance.toFixed(2)} RUB\n\nЭтот баланс пополняется после успешной аренды ваших подарков.`,
    {
      reply_markup: {
        inline_keyboard: [
          [{ text: "💸 Вывести средства", callback_data: "withdraw" }],
          [{ text: "◀️ Назад", callback_data: "home" }]
        ]
      }
    }
  );
});

bot.action("catalog", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  const listings = await getListings();

  if (!listings.length) {
    await ctx.editMessageText(
      "🎁 Сейчас нет доступных подарков для аренды.\n\nВладелец подарка может нажать «🎁 Сдать в аренду».",
      { reply_markup: { inline_keyboard: [[{ text: "◀️ Назад", callback_data: "home" }]] } }
    );
    return;
  }

  const rows = listings.map(item => [{
    text: `🎁 ${item.title} — ${Number(item.price).toFixed(2)} ₽ / ${item.duration_days} д.`,
    callback_data: `rent:${item.id}`
  }]);

  rows.push([{ text: "◀️ Назад", callback_data: "home" }]);
  await ctx.editMessageText("🎁 Доступные подарки:", { reply_markup: { inline_keyboard: rows } });
});

bot.action(/^rent:(\d+)$/, async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  const listing = await getListing(Number(ctx.match[1]));

  if (!listing) {
    await ctx.editMessageText("❌ Это объявление больше недоступно.");
    return;
  }

  await ctx.replyWithInvoice({
    title: `Аренда: ${listing.title}`,
    description: `Аренда уникального подарка на ${listing.duration_days} д.`,
    payload: JSON.stringify({ type: "rental", listingId: listing.id, renterId: ctx.from.id }),
    currency: "XTR",
    prices: [{ label: `Аренда ${listing.title}`, amount: Math.max(1, Math.round(Number(listing.price))) }]
  });
});

bot.on("pre_checkout_query", async (ctx) => {
  const payload = JSON.parse(ctx.update.pre_checkout_query.invoice_payload || "{}");
  if (payload.type !== "rental") {
    await ctx.answerPreCheckoutQuery(false, "Неизвестный платёж.");
    return;
  }
  const listing = await getListing(Number(payload.listingId));
  if (!listing) {
    await ctx.answerPreCheckoutQuery(false, "Подарок уже недоступен.");
    return;
  }
  await ctx.answerPreCheckoutQuery(true);
});

bot.on("successful_payment", async (ctx) => {
  try {
    const payment = ctx.message.successful_payment;
    const payload = JSON.parse(payment.invoice_payload || "{}");
    if (payload.type !== "rental") return;

    const listing = await getListing(Number(payload.listingId));
    if (!listing) {
      await ctx.reply("⚠️ Платёж получен, но объявление уже недоступно. Обратитесь в поддержку.");
      return;
    }

    const rentalId = await recordRentalAndCredit(listing, ctx.from.id);
    await ctx.reply(
      `✅ Аренда оплачена!\n\n🎁 ${listing.title}\n📅 Срок: ${listing.duration_days} д.\n💰 Владелец получил ${Number(listing.price).toFixed(2)} ₽ на баланс бота.\n🧾 Аренда №${rentalId}`,
      mainKeyboard()
    );
  } catch (err) {
    console.error("successful_payment error:", err);
    await ctx.reply("⚠️ Платёж получен, но обработка аренды завершилась с ошибкой. Обратитесь в поддержку.");
  }
});

bot.action("rent_out", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  await ctx.editMessageText(
    termsText(),
    termsKeyboard()
  );
});

bot.on("message", async (ctx, next) => {
  const message = ctx.message || {};
  const uniqueGiftInfo = message.unique_gift;

  if (uniqueGiftInfo && uniqueGiftInfo.gift) {
    try {
      await ensureUser(ctx);

      const gift = uniqueGiftInfo.gift;
      const title = gift.name
        ? "NFT " + gift.name + (gift.number ? " #" + gift.number : "")
        : (gift.base_name || "Уникальный Telegram-подарок");

      const listingId = await createListing(ctx.from.id, title, 0, 1, "pending");
      states.set(ctx.from.id, {
        step: "gift_price",
        listingId,
        title,
        termsAccepted: true,
        uniqueGift: {
          name: gift.name || "",
          number: gift.number || 0,
          base_name: gift.base_name || "",
          origin: uniqueGiftInfo.origin || ""
        }
      });

      await ctx.reply(
        "🎁 NFT получен!\n\n" +
        "🧾 Автоматически создан запрос на аренду №" + listingId + ".\n" +
        "🎁 " + title + "\n\n" +
        "💰 Теперь напишите цену аренды в рублях:"
      );

      if (ADMIN_TELEGRAM_ID) {
        try {
          await bot.telegram.sendMessage(
            ADMIN_TELEGRAM_ID,
            "📥 Новый автоматический запрос на аренду NFT №" + listingId +
            "\n👤 Владелец: " + (ctx.from.username ? "@" + ctx.from.username : ctx.from.id) +
            "\n🆔 ID: " + ctx.from.id +
            "\n🎁 " + title
          );
        } catch (e) {
          console.error("gift admin notification error:", e);
        }
      }
    } catch (err) {
      console.error("unique_gift handler error:", err);
      await ctx.reply("⚠️ NFT получен, но запрос на аренду не удалось создать. Обратитесь в поддержку.");
    }
    return;
  }

  return next();
});

bot.on("text", async (ctx, next) => {
  const state = states.get(ctx.from.id);
  if (!state) return next();

  const text = ctx.message.text.trim();

  if (state.step === "complaint") {
    const cid=await createComplaint(ctx.from.id,text.slice(0,1000)); states.delete(ctx.from.id);
    await ctx.reply(`✅ Жалоба №${cid} принята. Администрация рассмотрит её.`,mainKeyboard());
    if(ADMIN_TELEGRAM_ID) await bot.telegram.sendMessage(ADMIN_TELEGRAM_ID,`🚨 Новая жалоба №${cid}\\n👤 ID: ${ctx.from.id}\\n📋 ${text.slice(0,1000)}`);
    return;
  }

  if (state.step === "media_photo") {
    if (!ctx.message.photo || !ctx.message.photo.length) {
      await ctx.reply("❌ Отправьте именно фотографию.");
      return;
    }
    const photo=ctx.message.photo[ctx.message.photo.length-1];
    await saveMedia(state.mediaKey,photo.file_id);
    const key=state.mediaKey;
    states.delete(ctx.from.id);
    await ctx.reply(`✅ Картинка для «${key}» сохранена.`);
    return;
  }

  if (state.step === "admin_password") {
    if (!adminOnly(ctx)) { states.delete(ctx.from.id); return; }
    if (!ADMIN_PANEL_PASSWORD || text !== ADMIN_PANEL_PASSWORD) {
      states.delete(ctx.from.id); await ctx.reply("❌ Неверный пароль. Доступ закрыт."); return;
    }
    states.delete(ctx.from.id);
    await ctx.reply("🔐 Админ-панель открыта.",{reply_markup:{inline_keyboard:[
      [{text:"💸 Заявки на вывод",callback_data:"admin:withdrawals"}],
      [{text:"🔄 Вернуть NFT",callback_data:"admin:return"}],
      [{text:"🚨 Жалобы",callback_data:"admin:complaints"}],
      [{text:"⭐ Начислить Stars",callback_data:"admin:stars"}],
      [{text:"🔒 Заблокировать аккаунт",callback_data:"admin:block"}],
      [{text:"⚠️ Дать предупреждение",callback_data:"admin:warn"}],
      [{text:"👤 Профиль пользователя",callback_data:"admin:profile"}]
    ]}});
    return;
  }

  if (state.step === "admin_stars") {
    const [uid,amount]=text.split(/\s+/); const n=Number(uid), a=Number(amount);
    if(!Number.isInteger(n)||!Number.isFinite(a)||a<=0){await ctx.reply("❌ Формат: ID количество");return;}
    await addStars(n,a); states.delete(ctx.from.id); await ctx.reply(`✅ Пользователю ${n} начислено ⭐ ${a} Stars.`); try{await bot.telegram.sendMessage(String(n),`⭐ Вам начислено ${a} Stars администрацией.`);}catch(e){} return;
  }
  if (state.step === "admin_block") {
    const n=Number(text); if(!Number.isInteger(n)){await ctx.reply("❌ Неверный Telegram ID.");return;}
    await setBlocked(n,true); states.delete(ctx.from.id); await sendVisual(ctx, "blocked", `🔒 Пользователь ${n} заблокирован.`); try{await bot.telegram.sendMessage(String(n),"🔒 Ваш аккаунт заблокирован администрацией.");}catch(e){} return;
  }
  if (state.step === "admin_warn") {
    const [uid,...rest]=text.split("|"); const n=Number(uid.trim()), reason=rest.join("|").trim();
    if(!Number.isInteger(n)||!reason){await ctx.reply("❌ Формат: ID | причина");return;}
    await addWarning(n,reason,ctx.from.id); states.delete(ctx.from.id); await sendVisual(ctx, "warning", `⚠️ Предупреждение выдано пользователю ${n}.`); try{await bot.telegram.sendMessage(String(n),`⚠️ Вам выдано предупреждение.\\nПричина: ${reason}`);}catch(e){} return;
  }
  if (state.step === "admin_profile") {
    const n=Number(text); if(!Number.isInteger(n)){await ctx.reply("❌ Неверный Telegram ID.");return;}
    const p=await getProfile(n); const u=p.user; states.delete(ctx.from.id);
    if(!u) return ctx.reply("❌ Пользователь не найден.");
    await sendVisual(ctx, "profile", `👤 Профиль ${n}\\n💰 Баланс: ${Number(u.balance||0).toFixed(2)} ₽\\n⭐ Stars: ${Number(u.stars_balance||0)}\\n⚠️ Предупреждений: ${Number(u.warnings||0)}\\n🔒 ${u.blocked?"Заблокирован":"Активен"}`);
    return;
  }
  if (state.step === "admin_return") {
    const n=Number(text); if(!Number.isInteger(n)){await ctx.reply("❌ Введите номер аренды.");return;}
    const r=await markRentalReturned(n); states.delete(ctx.from.id);
    if(!r) return ctx.reply("❌ Аренда не найдена или уже возвращена.");
    await sendVisual(ctx, "returnNft", `🔄 Возврат по аренде №${n} оформлен.\\n\\n⚠️ Передача NFT обратно владельцу должна быть выполнена через поддерживаемый Telegram-механизм передачи подарка.`);
    try{await bot.telegram.sendMessage(String(r.renter_id),`🔄 По аренде №${n} оформлен возврат NFT. Ожидайте дальнейших действий поддержки.`);}catch(e){}
    return;
  }
  if (state.step === "gift_price") {
    const price = Number(text.replace(",", "."));
    if (!Number.isFinite(price) || price <= 0) {
      await ctx.reply("❌ Введите корректную цену, например: 150");
      return;
    }
    state.price = price;
    state.step = "gift_duration";
    await ctx.reply("📅 Теперь напишите срок аренды в днях, например: 1, 7 или 30:");
    return;
  }

  if (state.step === "gift_duration") {
    const days = Number(text);
    if (!Number.isInteger(days) || days <= 0 || days > 365) {
      await ctx.reply("❌ Введите целое число дней от 1 до 365.");
      return;
    }

    const ok = await activateListing(state.listingId, state.price, days);
    if (!ok) {
      states.delete(ctx.from.id);
      await ctx.reply("❌ Запрос на аренду уже обработан или недоступен. Обратитесь в поддержку.");
      return;
    }

    const listingId = state.listingId;
    const title = state.title;
    const price = state.price;
    states.delete(ctx.from.id);

    await ctx.reply(
      "✅ NFT автоматически добавлен в запрос на аренду!\n\n" +
      "🧾 Запрос №" + listingId + "\n" +
      "🎁 " + title + "\n" +
      "💰 Цена: " + price.toFixed(2) + " ₽\n" +
      "📅 Срок: " + days + " д.\n\n" +
      "Теперь его можно арендовать из каталога.",
      mainKeyboard()
    );
    return;
  }

  if (state.step === "title") {
    state.title = text.slice(0, 100);
    state.step = "price";
    await ctx.reply("💰 Напишите цену аренды в рублях за выбранный срок:");
    return;
  }

  if (state.step === "price") {
    const price = Number(text.replace(",", "."));
    if (!Number.isFinite(price) || price <= 0) {
      await ctx.reply("❌ Введите корректную цену, например: 150");
      return;
    }
    state.price = price;
    state.step = "duration";
    await ctx.reply("📅 Напишите срок аренды в днях, например: 1, 7 или 30:");
    return;
  }

  if (state.step === "duration") {
    const days = Number(text);
    if (!Number.isInteger(days) || days <= 0 || days > 365) {
      await ctx.reply("❌ Введите целое число дней от 1 до 365.");
      return;
    }

    const listingId = await createListing(ctx.from.id, state.title, state.price, days);
    states.delete(ctx.from.id);

    await ctx.reply(
      `✅ Подарок выставлен в аренду!\n\n🎁 ${state.title}\n💰 Цена: ${state.price.toFixed(2)} ₽\n📅 Срок: ${days} д.\n\nПосле успешной оплаты аренды деньги будут зачислены на ваш баланс бота.`,
      mainKeyboard()
    );
    return;
  }

  if (state.step === "withdraw_amount") {
    const amount = Number(text.replace(",", "."));
    const balance = await getBalance(ctx.from.id);

    if (!Number.isFinite(amount) || amount <= 0) {
      await ctx.reply("❌ Введите корректную сумму.");
      return;
    }
    if (amount > balance) {
      await ctx.reply(`❌ Недостаточно средств. Ваш баланс: ${balance.toFixed(2)} ₽`);
      return;
    }

    state.amount = amount;
    state.step = "withdraw_method";
    await ctx.reply("💳 Напишите способ получения выплаты (например, СБП или банковская карта):");
    return;
  }

  if (state.step === "withdraw_method") {
    state.method = text.slice(0, 50);
    state.step = "withdraw_details";
    await ctx.reply("🔐 Напишите реквизиты для выплаты. Не отправляйте сюда пароль или код подтверждения Telegram.");
    return;
  }

  if (state.step === "withdraw_details") {
    const ok = await subtractBalance(ctx.from.id, state.amount);
    if (!ok) {
      states.delete(ctx.from.id);
      await ctx.reply("❌ Не удалось зарезервировать сумму для вывода. Попробуйте ещё раз.");
      return;
    }

    const wid = await createWithdrawal(ctx.from.id, state.amount, state.method, text.slice(0, 300));
    states.delete(ctx.from.id);

    await ctx.reply(
      `✅ Заявка на вывод №${wid} создана.\n\n💰 Сумма: ${state.amount.toFixed(2)} ₽\n💳 Способ: ${state.method}\n\nПосле проверки заявка будет обработана.`,
      mainKeyboard()
    );

    if (ADMIN_TELEGRAM_ID) {
      await bot.telegram.sendMessage(
        ADMIN_TELEGRAM_ID,
        `💸 Новая заявка на вывод №${wid}\n\n👤 Пользователь: ${ctx.from.username ? "@" + ctx.from.username : ctx.from.id}\n🆔 ID: ${ctx.from.id}\n💰 Сумма: ${state.amount.toFixed(2)} ₽\n💳 Способ: ${state.method}\n📋 Реквизиты: ${text.slice(0, 300)}`
      );
    }
  }
});

bot.action("withdraw", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  const balance = await getBalance(ctx.from.id);

  if (balance <= 0) {
    await ctx.editMessageText(
      "💸 Вывод средств\n\nУ вас пока нет доступных средств для вывода.",
      { reply_markup: { inline_keyboard: [[{ text: "◀️ Назад", callback_data: "home" }]] } }
    );
    return;
  }

  states.set(ctx.from.id, { step: "withdraw_amount" });
  await editVisual(ctx, "withdrawal", `💸 Вывод средств\n\nДоступно: ${balance.toFixed(2)} ₽\n\nВведите сумму вывода:`
  );
});

bot.command("admin", async (ctx) => {
  if (!adminOnly(ctx)) return;
  states.set(ctx.from.id, { step: "admin_password" });
  await ctx.reply("🔐 Введите пароль для доступа к админ-панели:");
});

bot.command("withdrawals", async (ctx) => {
  if (!ADMIN_TELEGRAM_ID || String(ctx.from.id) !== String(ADMIN_TELEGRAM_ID)) return;
  states.set(ctx.from.id, { step: "admin_password" });
  await ctx.reply("🔐 Введите пароль для доступа к админ-панели:");
});
async function markRentalReturned(id) {
  if (pool) {
    const r=await dbQuery("UPDATE rentals SET status='returned' WHERE id=$1 AND status='paid' RETURNING renter_id,seller_id,listing_id",[id]);
    return r.rows[0] || null;
  }
  const r=memory.rentals.get(id);
  if(!r || r.status!=="paid") return null;
  r.status="returned"; return r;
}

function adminOnly(ctx) {
  return ADMIN_TELEGRAM_ID && String(ctx.from.id)===String(ADMIN_TELEGRAM_ID);
}

bot.action(/^admin:(withdrawals|return|complaints|stars|block|warn|profile|media)$/, async (ctx) => {
  await ctx.answerCbQuery();
  if(!adminOnly(ctx)) return ctx.reply("⛔ Нет доступа.");
  const action=ctx.match[1];
  if(action==="withdrawals") {
    const list=await getPendingWithdrawals();
    if(!list.length) return ctx.reply("💸 Заявок на вывод нет.");
    for(const w of list) await ctx.reply(`💸 Заявка №${w.id}\\n👤 ID: ${w.telegram_id}\\n💰 ${Number(w.amount).toFixed(2)} ₽\\n💳 ${w.method}\\n📋 ${w.details}`,{reply_markup:{inline_keyboard:[[{text:"✅ Одобрить",callback_data:`wd:approve:${w.id}`},{text:"❌ Отклонить",callback_data:`wd:reject:${w.id}`}]]}});
    return;
  }
  if(action==="media"){
    await ctx.reply("🖼 Выберите тип картинки:",{reply_markup:{inline_keyboard:[
      [{text:"Главное меню",callback_data:"media:welcome"},{text:"Профиль",callback_data:"media:profile"}],
      [{text:"Аренда",callback_data:"media:rental"},{text:"Условия",callback_data:"media:terms"}],
      [{text:"Жалобы",callback_data:"media:complaint"},{text:"Админка",callback_data:"media:admin"}],
      [{text:"Предупреждение",callback_data:"media:warning"},{text:"Блокировка",callback_data:"media:blocked"}],
      [{text:"Stars",callback_data:"media:stars"},{text:"Возврат NFT",callback_data:"media:returnNft"}],
      [{text:"Вывод",callback_data:"media:withdrawal"},{text:"Поддержка",callback_data:"media:support"}]
    ]}});
    return;
  }
  const prompts={
    return:"🔄 Введите номер аренды для оформления возврата NFT:",
    stars:"⭐ Введите через пробел: ID пользователя и количество Stars. Например: 123456789 50",
    block:"🔒 Введите Telegram ID пользователя для блокировки:",
    warn:"⚠️ Введите через |: ID пользователя | причина предупреждения",
    profile:"👤 Введите Telegram ID пользователя для просмотра профиля:"
  };
  if(action==="complaints"){
    const list=await getOpenComplaints();
    if(!list.length) return ctx.reply("🚨 Открытых жалоб нет.");
    for(const x of list) await ctx.reply(`🚨 Жалоба №${x.id}\\n👤 ID: ${x.telegram_id}\\n📋 ${x.text}`,{reply_markup:{inline_keyboard:[[{text:"✅ Закрыть",callback_data:`complaint:close:${x.id}`}]]}});
    return;
  }
  states.set(ctx.from.id,{step:"admin_"+action});
  await ctx.reply(prompts[action]);
});

bot.action(/^media:([A-Za-z]+)$/,async ctx=>{
  await ctx.answerCbQuery();
  if(!adminOnly(ctx)) return ctx.reply("⛔ Нет доступа.");
  const key=ctx.match[1];
  const allowed=["welcome","profile","rental","terms","complaint","admin","warning","blocked","stars","returnNft","withdrawal","support"];
  if(!allowed.includes(key)) return ctx.reply("❌ Неизвестный тип картинки.");
  states.set(ctx.from.id,{step:"media_photo",mediaKey:key});
  await ctx.reply(`🖼 Отправьте фотографию для раздела «${key}». Следующее фото будет сохранено и использовано ботом.`);
});

bot.action(/^complaint:close:(\d+)$/,async ctx=>{
  await ctx.answerCbQuery();
  if(!adminOnly(ctx)) return ctx.reply("⛔ Нет доступа.");
  await closeComplaint(Number(ctx.match[1]));
  await ctx.editMessageText("✅ Жалоба закрыта.");
});

bot.action(/^wd:(approve|reject):(\d+)$/, async (ctx) => {
  await ctx.answerCbQuery();
  if (!ADMIN_TELEGRAM_ID || String(ctx.from.id) !== String(ADMIN_TELEGRAM_ID)) {
    await ctx.reply("⛔ Нет доступа.");
    return;
  }

  const action = ctx.match[1];
  const id = Number(ctx.match[2]);
  const w = await getWithdrawal(id);

  if (!w || w.status !== "pending") {
    await ctx.editMessageText("ℹ️ Эта заявка уже обработана.");
    return;
  }

  if (action === "approve") {
    await updateWithdrawalStatus(id, "approved");
    await ctx.editMessageText(`✅ Заявка №${id} одобрена. Сумма: ${Number(w.amount).toFixed(2)} ₽`);
    try {
      await bot.telegram.sendMessage(
        String(w.telegram_id),
        `✅ Ваша заявка на вывод №${id} одобрена. Сумма: ${Number(w.amount).toFixed(2)} ₽. Выплата производится администратором.`
      );
    } catch (e) {
      console.error("withdrawal notification error:", e);
    }
    return;
  }

  const changed = await updateWithdrawalStatus(id, "rejected");
  if (!changed) {
    await ctx.editMessageText("ℹ️ Эта заявка уже обработана.");
    return;
  }

  await addBalance(w.telegram_id, Number(w.amount));
  await ctx.editMessageText(`❌ Заявка №${id} отклонена. Сумма возвращена пользователю.`);
  try {
    await bot.telegram.sendMessage(
      String(w.telegram_id),
      `❌ Заявка на вывод №${id} отклонена. ${Number(w.amount).toFixed(2)} ₽ возвращены на ваш баланс.`
    );
  } catch (e) {
    console.error("withdrawal notification error:", e);
  }
});

bot.action("home", async (ctx) => {
  await ctx.answerCbQuery();
  await ensureUser(ctx);
  await ctx.editMessageText("🎁 Главное меню:", mainKeyboard());
});

bot.action("rentals", async (ctx) => {
  await ctx.answerCbQuery();
  await ctx.editMessageText("📦 Раздел «Мои аренды» будет расширен после подключения полноценного управления сроком аренды.");
});

bot.action("stars", async (ctx) => {
  await ctx.answerCbQuery();
  await ctx.editMessageText("⭐ Пополнение Stars подключается через официальные Telegram Payments.");
});

bot.action("support", async (ctx) => {
  await ctx.answerCbQuery();
  await editVisual(ctx, "support", "💬 Поддержка: напишите сюда свой вопрос.");
});

app.get("/", (_req, res) => {
  res.json({ ok: true, service: "Telegram Gift Rental Bot" });
});

const PORT = process.env.PORT || 3000;

async function start() {
  try {
    await initDb();
    app.listen(PORT, () => {
      console.log(`Web server listening on ${PORT}`);
    });

    // Polling and webhook are mutually exclusive in Telegram.
    // Remove an old webhook automatically so the bot can receive messages.
    await bot.telegram.deleteWebhook({ drop_pending_updates: false });
    console.log("Telegram webhook cleared");

    await bot.launch({
      dropPendingUpdates: false,
      allowedUpdates: ["message", "callback_query", "pre_checkout_query"]
    });
    console.log("Telegram bot started and polling for updates");
  } catch (err) {
    console.error("Startup failed:", err);
    process.exit(1);
  }
}

start().catch((err) => {
  console.error("Fatal startup error:", err);
  process.exit(1);
});

process.once("SIGINT", () => bot.stop("SIGINT"));
process.once("SIGTERM", () => bot.stop("SIGTERM"));
